requirements_test.txt: require black >= 22.3.0
The Travis CI environment installed 22.1.0, which is broken:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "src/black/__init__.py", line 1423, in patched_main
  File "src/black/__init__.py", line 1409, in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (/home/travis/virtualenv/python3.8.3/lib/python3.8/site-packages/click/__init__.py)